# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFnsKCbsCKpaist-RGZA3MIn3AgUspC5
"""

name = 'John'
name2 = 'john'
print("Are name and name 1 equal?")
print (name == name2)

print("Are name and name3 different?")
print (name != name2)

print("Is name less than or equal to name2?")
print (name <= name2)

print("Is name3 greater than or equal to name 2?")
print (name >= name2)

print("Is name4 less than name?")
print (name2< name)

