# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFnsKCbsCKpaist-RGZA3MIn3AgUspC5
"""

x="Akshay kumar"
i=0
count=0
while i<len(x):
  count+=1
  i+=1
print("Number of charcters in a string=",count)