# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFnsKCbsCKpaist-RGZA3MIn3AgUspC5
"""

a=input("enter a string")
for i in a:
  print(i)

