# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFnsKCbsCKpaist-RGZA3MIn3AgUspC5
"""

count=1
k="Akshay kumar is a good boy"
for i in k:
  if(i==" "):
    count+=1
print(count)