# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFnsKCbsCKpaist-RGZA3MIn3AgUspC5
"""

count=1
a=input()
for i in a:
  if(i==" "):
    count+=1
    if(count>1):
      print("sub string is present")
    else:
      print("sub string is not present")