# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFnsKCbsCKpaist-RGZA3MIn3AgUspC5
"""

count=0
y="hello world"
for i in y:
  if(i=="o"):
    count+=1
print("noof times letter appear in the string=",count)

